config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'user_badges#index'
    resources :user_badges, only: [:index, :show] do
      resources :user_objectives, only: [:create]
    end
  resources :badges, only: [:index, :new, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :objectives
end

app/models/objective.rb
class Objective < ApplicationRecord
  belongs_to :badge
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_badges

  has_many :ongoing_badges, -> { where(completed: false) }, :class_name => 'UserBadge'
  has_many :completed_badges, -> { where(completed: true) }, :class_name => 'UserBadge'

  has_many :user_objectives, through: :user_badges
  after_create :add_badges

  def has_done_this?(objective)
    user_objectives.where(objective: objective).any?
  end

  def add_badges
    Badge.all.each do |badge|
      UserBadge.create!(user: self, badge: badge)
    end
  end

end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
  has_many :user_objectives

  def all_objectives_done?
    badge.objectives.count == user_objectives.count
  end
end

app/models/user_objective.rb
class UserObjective < ApplicationRecord
  belongs_to :user_badge
  belongs_to :objective
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end

  def new
    
  end

  def create
  end

  def show
  end

  def update
  end
end

app/controllers/user_badges_controller.rb
class UserBadgesController < ApplicationController
  def index
    @userbadges = current_user.ongoing_badges
    @completed_badges = current_user.completed_badges
  end

  def show
    @userbadge = UserBadge.find(params[:id])
  end
end

app/controllers/user_objectives_controller.rb
class UserObjectivesController < ApplicationController
  def create
    @userbadge = UserBadge.find(params[:user_badge_id])
    user_objective = @userbadge.user_objectives.build(user_badge_params)
    user_objective.save
    if @userbadge.all_objectives_done?
      @userbadge.update(completed: true)
      @trigger_modal = true
    end
  end

  def user_badge_params
    params.permit(:objective_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def done_class(objective)
    current_user.has_done_this?(objective) ? "objective-done" : "objective-undone"
  end
end

app/views/badges/index.html.erb
<div class="container-fluid" id="badges-index">
  <div class="row" id="header-background">
    <div class="col-12 mb-5">
      <h1 id="title">INDEX DES BADGES</h1>
      <p>Liste des badges :</p>
    </div>
    <%= image_tag "medal.svg", height: "140%", id: "medal" %>
  </div>

  <div class="row d-sm-none" id="badges-cards">
    <% @badges.each do |badge| %>
      <div class="col-12 d-flex mb-2 justify-content-between badge-card">

        <div class="d-flex flex-column justify-content-end mb-3">
          <p class="badge-card-name"><%= badge.name %></p>
        </div>

        <div class="badge-icon-container d-flex align-items-center justify-content-center">
          <svg width="80" height="80" id="badgeicon<%= badge.id %>" >
              <defs>
                  <clipPath id="circleView">
                    <circle cx="40" cy="40" r="40" fill="#FFFFFF" /></circle>
                  </clipPath>
              </defs>
            <image width="80" height="80" xlink:href="<%= image_url(badge.icon_name) %>" clip-path="url(#circleView)" transform="scale(-1, -1) translate(-80, -80)" /></image>
          </svg>
        </div>

        <%= link_to "", badge_path(badge), class: "badge-card-show-link" %>
      </div>
    <% end %>
  </div>

  <div class="row d-none d-sm-block" id="badges-cards-sm">
    <% @badges.each do |badge| %>
      <div class="col-6 col-lg-4 d-flex mb-2 justify-content-between">
        <div class="d-flex flex-column justify-content-end mb-3">
          <p class=""><%= badge.name %></p>
        </div>
        <div class="d-flex align-items-center justify-content-center">
          <%= image_tag badge.icon_name %>
        </div>
        <%= link_to "", badge_path(badge), class: "badge-card-show-link" %>
      </div>
    <% end %>
  </div>
</div>

app/views/badges/new.html.erb
<h1>Badges#new</h1>
<p>Find me in app/views/badges/new.html.erb</p>

app/views/badges/show.html.erb
<h1>Badges#show</h1>
<p>Find me in app/views/badges/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="<%= image_url "favicon.png" %>" type="image/x-icon">
    <title>medQuest</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>
    <link rel="javascript" href="http://localhost:35729/livereload.js">
  </body>
</html>

app/views/user_badges/_bottom_slide_view.html.erb
<div class="bottom-view">
  <div class="bottom-view-container d-none">
    <div class="container d-flex flex-column justify-content-between">
      <div class="badge-group">
        <div class="row">
          <div class="col-12 text-center">
            <p id="badge-acquired-title">Vos badges acquis</p>
          </div>
        </div>
        <div class="row bottom-view-badges-container ">
          <% @completed_badges.each_with_index do |userbadge, index| %>
            <div class="col-4 mt-4 mb-5">

                <div class="badge-icon-container d-flex align-items-center justify-content-center" data-progress="">
                  <svg width="80" height="80" id="badgeicon<%= userbadge.badge.id %>" class='completed-achievements'>
                    <defs>
                      <clipPath id="circleView">
                        <circle cx="40" cy="40" r="40" fill="#FFFFFF" />
                      </clipPath>
                    </defs>
                    <image width="80" height="80" xlink:href="<%= image_url(userbadge.badge.icon_name) %>" clip-path="url(#circleView)" transform="scale(-1, -1) translate(-80, -80)" />
                  </svg>
                </div>
              <%= link_to "", user_badge_path(userbadge), class: "badge-show-link" %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row align-text-bottom">
        <div class="col-12 text-right" id="collapse">
          <%= image_tag "chevrondown.svg", height: "20px;" %>
        </div>
      </div>
    </div>

  </div>
</div>

<!-- TRIGGER -->
<script>
  $('.bottom-view').click(function() {
    $(this).toggleClass('expanded');
    $('.bottom-view-container').toggleClass('d-none');
  })
</script>

app/views/user_badges/_icon_container.html.erb
<div class="badge-icon-container d-flex align-items-center justify-content-center" data-progress="">
  <svg width="80" height="80" class='completed-achievements'>
      <defs>
          <clipPath id="circleView">
            <circle cx="40" cy="40" r="40" fill="#FFFFFF" />
          </clipPath>
      </defs>
    <image width="80" height="80" xlink:href="<%= image_url(icon) %>" clip-path="url(#circleView)" />
  </svg>
</div>

app/views/user_badges/index.html.erb
<div class="container-fluid" id="userbadge-index">
  <div class="row" id="header-background">
    <div class="col-7 mb-5">
      <h1 id="title">RIBERAQUEST</h1>
      <p>Liste de vos badges :</p>
    </div>
    <div class="col-5">
      <%= image_tag "favicon.png", height: "150%", id: "medal" %>
    </div>
  </div>

  <div class="row" id="badges-cards">
    <% @userbadges.each do |userbadge| %>
      <div class="col-12 d-flex mb-2 justify-content-between badge-card">

        <div class="d-flex flex-column justify-content-end mb-3">
          <p class="badge-card-name"><%= userbadge.badge.name %></p>
          <p class="progression"><%= "#{userbadgeobjectifcount = userbadge.user_objectives.count}/#{badgeobjectifcount = Badge.find(userbadge.badge_id).objectives.count}" %></p>
        </div>

        <% progressionRequested = ((userbadgeobjectifcount / badgeobjectifcount.to_f).round(2)) %>

        <div class="badge-icon-container d-flex align-items-center justify-content-center" data-progress="<%= progressionRequested if progressionRequested != nil %>">
          <svg width="80" height="80" id="badgeicon<%= userbadge.badge.id %>" class="<%= 'completed-achievements' if progressionRequested == nil %>">
              <defs>
                  <clipPath id="circleView">
                    <circle cx="40" cy="40" r="40" fill="#FFFFFF" />
                  </clipPath>
              </defs>
            <image width="80" height="80" xlink:href="<%= image_url(userbadge.badge.icon_name) %>" clip-path="url(#circleView)" transform="scale(-1, -1) translate(-80, -80)" />
          </svg>
        </div>

        <%= link_to "", user_badge_path(userbadge), class: "badge-card-show-link" %>
      </div>
    <% end %>
    <div class="col-12 d-flex align-items-center justify-content-center badge-card" id="badge-new">
        <p id="plus">+</p>
      <%= link_to "", badges_path, class: "badge-card-show-link" %>
  </div>
</div>
<%= render 'bottom_slide_view' %>

app/views/user_badges/show.html.erb
<div class="container-fluid" id="userbadgeshow">
  <div class="row" id="header-background">
    <div class="col-7 mb-5">
      <%= link_to user_badges_path do %>
        <%= image_tag "chevronleft.svg", height: "20px;", class: "mt-4", id: "badge-image" %>
      <% end %>
      <h1 id="title"><%= @userbadge.badge.name %></h1>
      <p>Objectifs :</p>
    </div>
    <div class="col-5">
      <%= image_tag @userbadge.badge.icon_name, height: "100%" %>
    </div>
  </div>

  <div class="row" id="badges-cards">
   <div class="col-12 " id="accordion">
    <%= render 'user_objectives/accordion_index' %>
  </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
      </div>
      <div class="modal-body">
        <div class="modal-icon">
          <%= render partial: 'icon_container', locals: { icon: @userbadge.badge.icon_name } %>
        </div>
        <h3 class='text-center'>
          Félicitations !
          Vous venez de débloquer le badge : <%= @userbadge.badge.name %>
        </h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-modal" data-dismiss="modal">Ajouter ce badge !</button>
      </div>
    </div>
  </div>
</div>

app/views/user_objectives/_accordion_index.html.erb
<% @userbadge.badge.objectives.each do |objective| %>
  <div class="d-flex mt-3 mb-1 justify-content-between badge-card accordion-toggle">
    <div class="d-flex flex-column justify-content-end badge-card-details">
      <p class="badge-card-name"><%= objective.name %></p>
    </div>
    <div class="d-flex align-items-center text-center mr-5">
      <i class='fa fa-check-circle-o <%= done_class(objective) %>'></i>
    </div>
    <!-- class undone for undone css -->
  </div>

  <div class="objective-decription accordion-content ml-3">
    <p class="objective-decription-content mb-3"><%= objective.description  %></p>
    <% if !current_user.has_done_this?(objective) %>
      <%= link_to user_badge_user_objectives_path(@userbadge, objective_id: objective.id), method: :post, remote: true do %>
      <div class="modal-content-icons d-flex justify-content-between">
        <button type="button" class="btn btn-primary">J'ai réalisé ce défi !</button>
        <i class='fa fa-info-circle awe-info' ></i>
      </div>
      <% end %>
    <% end %>
  </div>
<% end %>

<!-- JS -->
<script type="text/javascript">
  $(document).ready(function($) {
    $('#accordion').find('.accordion-toggle').click(function(){
      //Expand or collapse this panel
      $(this).next().slideToggle('fast');
      //Hide the other panels
      $(".accordion-content").not($(this).next()).slideUp('fast');
    });
  });
</script>

app/views/user_objectives/create.js.erb
$('#accordion').html("<%= j(render 'accordion_index') %>")
<% if @trigger_modal %>
  $('#myModal').modal('show');
<% end %>